spring:
  application:
    name: alert-service

  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db
    username: postgres
    password: pass@123

  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  flyway:
    enabled: true
    schemas: alert
    default-schema: alert

  jackson:
    time-zone: Asia/Kolkata

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: alert
      hibernate.jdbc.time_zone: UTC
    show-sql: true

server:
  port: 8080