spring:
  application:
    name: alert-service

  datasource:
    url: jdbc:postgresql://localhost:5432/incident_db
    username: postgres
    password: pass@123

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none